### ISSUE TITLE
Plan for common parts

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#1]
The following are common parts of the Technical Framework that are published at the same level as the domain folders:

- General Introduction 
- Appendix A: Actors
- Appendix B: Transactions
- Appendix C: IHE Namespaces
- Appendix D: Glossary
- Appendix E: Profiling 
- Appendix F: Integration Statements

**Comment by JohnMoehrke** [comment]
@MaryLJ Where can we find DOCX versions of these general pages? I did not find them on the google drive in the DocumentPublication folder
    https://drive.google.com/drive/u/0/folders/1M3i4R8iyxqIe_hctkJCPIFtDlVF-kQsB

**Comment by JohnMoehrke** [comment]
@MaryLJ where can we find the docx of these common appendix?

**Comment by JohnMoehrke** [comment]
These should appear as html files in the root of the publications with links to these html from the index.html there.

**Comment by msmock** [comment]
added the general introduction including appendix C, E and F
