### ISSUE TITLE
Appendix E.3 needs a new TI home

### ISSUE THREAD

**Issue by lynnfel** [IHE/publications#110]
When Appendix Z was republished in HTML Format, Section  E.3 (Usage of the CX Data Type in PID-3 Patient Identifier List), which was in the original Appx Z  PDF (https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_Suppl_Appx-Z.pdf)  was left without a home.

We need   to find a new Trial Implementation publication (eg PIXm) to contain Appx E.3.

Alternatively, we could consider adding E.3 into existing Vol 3 Appx E,  with a  TI marking.

When we decide on the location, existing references to E.3 should be updated to point there  (eg add a hyperlink)

**Comment by oliveregger** [comment]
I would propose at TI marking similar is done with the [TU] marking in FHIR: http://hl7.org/fhir/capabilitystatement.html#search

```
<a style="padding-left: 3px; padding-right: 3px; border: 1px grey solid; font-weight: bold; color: black; background-color: #fff5e6" href="https://wiki.ihe.net/index.php/Technical_Framework_Publication_Process#Trial_Implementation" title="Trial Implmementation">TI</a>
```

**Comment by JohnMoehrke** [comment]
I think this would be helpful, especially to have it be a link to someplace that explained TI vs FT.

Not sure the [TU] marking that is used in FHIR is helpful for this use-case. This is whole section that is being inserted into an appendix. 

I was expecting the whole inserted section would have a different background (like a light grey background) to indicate TI marking. This would then be visible regardless of the size of device the user is useing. For example a user that has a deep link to a sub-section where they are using a small form-factor (cellular phone). Thus they might not notice a marking on the Header.

**Comment by lynnfel** [comment]
When this is resolved, this section contains a link to fix:  http://build.fhir.org/ig/IHE/ITI.PDQm/branches/main/ITI-78.html#23784124-populating-which-domains-are-returned
