### ISSUE TITLE
fix banner text speaking about PDF

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#111]
The current version of the ITI Technical Framework is published here in HTML format. The ITI Technical Framework and the existing supplements are also published as PDF files.
Differences between PDF and HTML are unintended. PDF takes precedence.

**Comment by JohnMoehrke** [comment]
Should we just remove this banner completely? Or should we change it to indicate the html is now the only formal specification? @lynnfel @lukeaduncan

**Comment by lynnfel** [comment]
I think we can remove it (feeling brave).   

We also are not creating a Rev 18 in PDF, so there's no PDF to 'take precedence' that will be equivalent to the updated HTML.

**Comment by JohnMoehrke** [comment]
Change to

"The Final Text ITI Technical Framework is published here in HTML format and is no longer published as PDF. Trial Implementation supplements are available from the Volume 1 table of contents."

Note, this warning bar will go away next year

**Comment by JohnMoehrke** [comment]
Done with Rev 18
