### ISSUE TITLE
Vol 2, Figure 3.55.4.2.2.6-1 is missing

### ISSUE THREAD

**Issue by lynnfel** [IHE/publications#113]
During CP integration review, I noticed that Vol 2 Figure 3.66.4.2.2.6-1 is missing.

I found it in CP-ITI-1212:  https://docs.google.com/document/d/1woPRoBqEsCR5YXzrkfbPSAKi75l3eJsK/edit

**Comment by JohnMoehrke** [comment]
The figure was in github but with a bad filename "FIgure.." rather than "Figure..."
