### ISSUE TITLE
Footnote handling

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#12]
The export put all footnotes at the end of the last chapter. So for Volume1 this ended up in ch-68 (which is now ch-Glossary). In html form we should be handling footnotes differently. 
Can we bring these footnotes in as simply inline notes?
What alternatives are the reader going to expect?

**Comment by JohnMoehrke** [comment]
details
* Volume 1 has 11 footnotes
* Volume 2a has no footnotes
* Volume 2b has ONE footnote called for in ITI-55 that is tacked onto ITI-64
* Volume 2x has 11 footnotes
* Volume 3 has 5 footnotes

**Comment by JohnMoehrke** [comment]
Recommend pulling the text into inline "Note: ..." style. Removing all footnote use.

**Comment by BenLevy62** [comment]
John, I like your suggestion.  If it's relevant info, put it in-line.  For Vol2b, the in-line note can have a link to the other section if needed.
