### ISSUE TITLE
Many broken links to HL7v3 in V3 Profiles

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/publications#120]
The message information model tables in the V3 Profiles have many broken links to various versions of HL7 V3:

![image](https://user-images.githubusercontent.com/68654017/138990237-5fb6ddbd-2aec-475b-9fb8-217472ec66e5.png)

I checked both PDQv3 and XCPD and found these all over; not sure if there are others. 

Funnily enough, this is not a new issue with the move to web. These links also exist in the old PDFs, but aren't as noticeable because they look like normal text. 

![image](https://user-images.githubusercontent.com/68654017/138990393-167a1503-21b3-4f2a-9cea-711210c1185f.png)

Given the fact that this isn't a transition bug, not sure if this needs a CP or if a GitHub issue will suffice.

**Comment by jlamy** [comment]
I'd like to say that we could make this more palatable to HL7 by only asking them to host the parts that IHE references: the specific messages & wrappers, the specific topics (Patient, Transmissions, etc.), and the data types used (abstract and XML), but sifting those out might be more effort than just giving a dedicated hosted copy. Also, they could host the content in the HL7 website and require login.

**Comment by JohnMoehrke** [comment]
I suspect we need to create a page specific to HL7 v3 specification availability. Have all our current links go to this page. And have this page express the HL7 plan to retire V3, and the HL7 process for making the [V3 specification available only to members](http://www.hl7.org/documentcenter/private/standards/v3/edition_web/welcome/environment/index.html).
or possibly just change all links to https://www.hl7.org/implement/standards/product_brief.cfm?product_id=186

**Comment by JohnMoehrke** [comment]
https://chat.fhir.org/#narrow/stream/179160-social/topic/HL7.20v3

**Comment by JohnMoehrke** [comment]
Found 567 instances of links starting with - `http://hl7.org/v3ballot2007may/html`  (likely not proper)
Volume2/ch-O.html
Volume2/ITI-45.html
Volume2/ITI-47.html
Volume2/ITI-55.html

**Comment by slagesse-epic** [comment]
The current links are super inconsistent though. Some datatypes are linked, some are not. I think we should remove most of the deep links entirely and simply have a high level link to  https://www.hl7.org/implement/standards/product_brief.cfm?product_id=186.

I don't think anybody thought there should be links in those tables until they started appearing clickable in the HTML version.

**Comment by JohnMoehrke** [comment]
I agree...  Removing the links (keep narrative), and just pointing them to the HL7 v3 landing.

**Comment by JohnMoehrke** [comment]
I will put in a pull-request with just changing from v3ballot2007 to v3ballotarchive.
change `http://hl7.org/v3ballot2007may/html` to `http://hl7.org/v3ballotarchive/v3ballot/html`

**Comment by JohnMoehrke** [comment]
Two alternative pull-requests.
