### ISSUE TITLE
Need hosted HTML archive

### ISSUE THREAD

**Issue by jlamy** [IHE/publications#122]
Some consumers of the Technical Framework need to be able to reference specific hosted releases of the TF by URL. They are currently able to accomplish this for the PDF versions of the TF via the archived versions. We need a similar capability for HTML content.

I'd request the following:
- Permalinks for version-specific content
- Section anchors that continue to function in the archive

**Comment by JohnMoehrke** [comment]
see #6 for alternatives. No solution is obvious and supported. Current use of github release versions is the only solution today.
