### ISSUE TITLE
Gazelle as Transaction directory

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#14]
https://gazelle.ihe.net/GMM/tf/transaction/listTransactions.seam

**Comment by JohnMoehrke** [comment]
@MaryLJ  is this done?

**Comment by MaryLJ** [comment]
The PDF has been retired and we now point to Gazelle in Appendix B and the wiki page that provides guidance on Browsing in Gazelle. Gazelle is the master repository for transactions.
