### ISSUE TITLE
Table 3.55.4.1.2.2-1: Model Attributes has broken HL7 links

### ISSUE THREAD

**Issue by DavidPyke** [IHE/publications#159]
All the links in the first column point to http://hl7.org/v3ballot2007may which no longer exists.  All links will need to be removed as the content is now only available in downloadable PDFs.

**Comment by JohnMoehrke** [comment]
This has been reported, but there is no alternative available to point at. HL7 does not publish v3 anymore.

**Comment by JohnMoehrke** [comment]
see #120

**Comment by JohnMoehrke** [comment]
closing this one as the work will continue in #120
