### ISSUE TITLE
Curly and straight quotes

### ISSUE THREAD

**Issue by qligier** [IHE/publications#165]
There's a mix of curly (‘ ’ “ ”) and straight (' ") quotes in the documents.
Pure text parts can use the one or the others (it's not always uniform).
Technical parts should use the straight ones (XML and other languages only use them).

**Comment by JohnMoehrke** [comment]
I did global search and replace on the ITI/TF; half of the html files gets modified (108/235), many thousands of changes.  Not clear to me what the benefit of a bulk change like that is. Would seem to me more appropriate to try to keep these from being used in new materials and to correct them when they cause trouble.

**Comment by MaryLJ** [comment]
> > > Mary, it seems you specifically put the curly (’) in in plural places. So global search and replace is not easy to do... e.g. Supplier’s. I don't even know how to get type that character.
> > 
> > 
> > Can you give me a specific IG to look at. I do not recall "explicitly" adding them.
> 
> I noticed when I looked to global search and replace in PDQm. I changed the curly double to straight double. But then I found the curly plural. So look at that as an example. I don't see anything wrong with any of the possibilities. I really think this should simply be style. Note that there is the markdown use of the back-single-quote, that we will use going forward for anything that we expect a programmer cares about.

I think those may be carry-overs from Word. When I type a ' or  "" on my keyboard in Notepad++, they are straight. I am not doing anything to make them curly.

Office products (Word, Outlook, PPT, etc.) default to curly but I see there is a way to change that default to straight, so I will change the default for my Office products. 

I will also add a item to my checklist to look for curly.

**Comment by JohnMoehrke** [comment]
do you agree that the resolution to this specific Issue is nothing more than you adding this to your checklist? As in, we should not change everything, there is just not enough benefit to that vs the perception that change has happened.

**Comment by MaryLJ** [comment]
> do you agree that the resolution to this specific Issue is nothing more than you adding this to your checklist? As in, we should not change everything, there is just not enough benefit to that vs the perception that change has happened.

Yes, I agree.

**Comment by MaryLJ** [comment]
It might also be of benefit to add a mention of this in the conversion instructions. When converting a Word doc to markdown or html, maybe change the ' and "" in the Word doc before the conversion or mention to look for them after the conversion.

**Comment by JohnMoehrke** [comment]
I didn't see a good place to put that, but also note that there are many different guidance today. I think it would be better to have a style-guide published that we place all style guidance.  then all of the author instructions can point at the style-guide.

**Comment by MaryLJ** [comment]
> I didn't see a good place to put that, but also note that there are many different guidance today. I think it would be better to have a style-guide published that we place all style guidance. then all of the author instructions can point at the style-guide.

OK
