### ISSUE TITLE
consistent handling of registered trademarks

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#17]
in fixing footnotes, I find that volume 2x and 4 used footnotes for the  set of registered trademarks, yet the other versions sometimes had it as inline statements. Seems we need to have this stated ONCE and not scattered everywhere and in different ways.

HL7, FHIR, CDA, DICOM, etc...

**Comment by JohnMoehrke** [comment]
@MaryLJ do you have a suggestion on registered trademarks?

**Comment by MaryLJ** [comment]
They should not be in footnotes. Each TF Volume now has an upfront section for the trademark info.

**Comment by JohnMoehrke** [comment]
@MaryLJ 
so we would only need to say this once in the Volume specific index.html file. Where we can say it about all... thus I can remove the statements elsewhere?
I don't find this text yet in our index.html... so do you have a block of these statements for everything ?

**Comment by MaryLJ** [comment]
Each Volume has a a section with the copyright info:
- Vol.1 -> Section 1.7
- Vol. 2 -> Section 1.6
- Vol. 3 -> Section 1.5
- Vol. 4 -> Section 1.5 
The current PDF published version of the ITI TF does have this info in Vol. 1 and 2 but not 3 and 4. I can supply the Word content as needed.

**Comment by JohnMoehrke** [comment]
john to remove all added notes, so as to rely on these general mentions of copyright and trademark
