### ISSUE TITLE
need extract automation documented

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#21]
for the benefit of ourselves in the future as supplements move to Final Text, and for ALL the other IHE domains that chose to follow us.

Document the process and tools used to auto extract from the DOCX to the html.

**Comment by JohnMoehrke** [comment]
I do find some of this in the readme. but we need this documented in the github wiki so that it can be found more broadly
   https://github.com/IHE/publications/blob/master/ITI/TF/readme.md

**Comment by msmock** [comment]
As discussed in the first meeting, the code is quick and dirty, depends on the details of the ITI TF formatting, and ugly to some extend. It has no error handling, has much code duplication and should be buried when the job is done. It's of practical no use for other and should be no means found by others (or I have to render the authorship anonymous to avoid to be associated with). Thus, there should be no need for documentation.

**Comment by JohnMoehrke** [comment]
I understand. Can you simply write pseudocode that explains what it intends to do?

**Comment by msmock** [comment]
It quick and dirty code, but clean. Every line tells exactly what is does. Thus the code should be readable. Documenting with pseudocode is quite a big effort I currently cannot spend without disregarding other tasks.

**Comment by JohnMoehrke** [comment]
@msmock what was the tool you used to extract the word into html?

**Comment by msmock** [comment]
The initial word to html conversion was done with https://www.aconvert.com/document/pages-to-doc/ <https://www.aconvert.com/document/pages-to-doc/>

**Comment by JohnMoehrke** [comment]
started this page to address
https://github.com/IHE/publications/wiki/Converting-Final-Text-WORD-to-HTML

**Comment by lukeaduncan** [comment]
Documentation has been created in the wiki as linked in previous comment.
