### ISSUE TITLE
Make document type configurable in ihe_template.html

### ISSUE THREAD

**Issue by unixoid** [IHE/publications#226]
In the file `https://github.com/IHE/publications/wiki/files/ihe_template.html`, the document type is hardcoded as "IHE HIE Whitepaper" (see line 70).  This needs to be configurable, because the template is used for other types of documents as well, see https://github.com/IHE/publications/issues/230.

**Comment by JohnMoehrke** [comment]
This is just a starter template. Today the output html is edited by @MaryLJ  to align with the actual work published.

That said, it would be nice if you would like to put forward a pull-request with advances to our very basic beginnings.

**Comment by JohnMoehrke** [comment]
fixed in the template and closed peer.
