### ISSUE TITLE
Quality check against current PDF

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#23]

**Comment by MaryLJ** [comment]
Link to Google sheet to track progress of quality check per file:
https://docs.google.com/spreadsheets/d/1eM8OgzO8qGbc9Q8lEyBtwdALFOaYZN9W-AsyV6EnXWA/edit#gid=0

**Comment by JohnMoehrke** [comment]
I have added all the files to the spreadsheet.

**Comment by JohnMoehrke** [comment]
I think that a column for each person doing reviews, simply marking those that individual reviewed. I certainly don't want to classify the reviewing that I do.

**Comment by JohnMoehrke** [comment]
I expect a core team reviewer will just FIX any problems they find, commit them to the github, and then mark the date they are done.... does that seem like a good process?
