### ISSUE TITLE
HIE Whitepaper listed in title above search bar

### ISSUE THREAD

**Issue by MaryLJ** [IHE/publications#230]
**Section Number** SeR page header

**Issue** title above search bar indicates HIE whitepaper

**Proposed Change** change to correctly state SeR Supplement

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
fixed the html template for long form to use the $title$ in this place that was missing using it with a hard coded text.
