### ISSUE TITLE
General Intro indicated Planning committee produces supplement

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#287]
I think that our General Introduction Chapter 8 is wrong on the first point

https://profiles.ihe.net/GeneralIntro/ch-8.html

It indicates that the Planning committee issues the supplements, and the technical committee resolves these comments. This is not how ITI works. Planning committee is responsible for managing the new work item queue, but nothing starts until the Technical committee agrees to start. It is the technical committee that develops the supplement and puts it out for public comment.

Meaning, I think that the wiki article is right, but not our general introduction 
https://wiki.ihe.net/index.php/Profile_Proposal_Process

Recommend the point be made more complete.

**Comment by kevino7** [comment]
Agree that the TC issues PC supps, which I think is how the sentence was intended to be read, i.e. that the “identified by the IHE planning committees” clarifies “new functionality” but the technical committee remains the subject of both verbs (develops & issues).
The shortest fix to make the intended meaning clear might be to add a comma, or we could add more words to reiterate the subject, e.g.:
 
1.      Each domain technical committee develops supplements to support new functionality identified by the IHE planning committees**,** and issues the supplement(s) for public comment. The technical committee addresses all comments received during the public comment period and publishes an updated version of the supplements for trial implementation. This version of the specification is used by vendors in developing trial implementation software for annual IHE Connectathon testing events.
 
1.      Each domain technical committee develops supplements to support new functionality **that was** identified by the IHE planning committees and **then the technical committee** issues the supplement(s) for public comment. The technical committee addresses all comments received during the public comment period and publishes an updated version of the supplements for trial implementation. This version of the specification is used by vendors in developing trial implementation software for annual IHE Connectathon testing events.
