### ISSUE TITLE
Adding Better Support for Specification Version Linking

### ISSUE THREAD

**Issue by ToddCooper** [IHE/publications#291]
## Publication Specification
Generally for all versioned IHE tech framework publications (both supplements and TF volumes).
Specifically (for this issue) the profiles.ihe.net/DEV/SDPi supplement versions

## Priority
Medium - Companies have workarounds by replicating all spec revisions in their in-house repositories, but that is a company-specific solution.

## Issue
Many companies have requirement management tools (e.g., DOORS) as part of their product tool chains, and these often require permalinks for identifying the specific version of a document in which the referenced requirement is located.  Given the typical multi-year lag between specification revisions and product releases (specifications are updated far faster than product implementations), there is a need to be able to reliably retain published versions of a specification to which a link may point.  Currently, profiles.ihe.net only publishes the most current version, with previous releases retained only in Github.

## Proposed Change
A similar issue is addressed in HL7 FHIR by providing a [Publication (Version) History page](http://hl7.org/fhir/directory.html).
Taking this approach, it would be relatively simple to:

1. Add subdirectories for each published release (e.g., profiles.ihe.net/DEV/SDPi/1.0.1/index.html) 
- NOTE:  The subdirectory can simply use the Github release label for its name
2. Link the "current" publication from the domain page to the most recent version
3. Add a published revisions page (a la the FHIR example above) with a table that we simply add to for each iteration) 

See related email thread between @d-gregorczyk  & @MaryLJ  + comments from @JohnMoehrke.

**Comment by JohnMoehrke** [comment]
I think we need to differentiate between Trial-Implementation and Final-Text. 

ITI does support version specific publications for Trial-Implementation phase; but not for Final-Text. For Final-Text our goal is to support only the current publication, allowing tagged github for historic. To support versions on Final-Text is to endorse our readers to use version specific Final-Text; which is very much against the principle of IHE Final-Text. ITI has seen very bad behavior and outcomes from this kind of version specific Final-Text; we do not want to encourage it.

see https://github.com/IHE/publications/wiki/Revision-Management
along with the other wiki articles on publications - https://github.com/IHE/publications/wiki

**Comment by ToddCooper** [comment]
@JohnMoehrke  - agree that there is a difference between TI and FT (integrated into the TF).  disagree that this would unduly "endorse" use of outdated / superseded versions, though I'm sure you have some pretty good "you gotta be kidding me" stories around this area.  

Reality is that products often lag "current" spec versions by years - and on a national basis, sometimes for a VERY long time (e.g., HL7 V2 nationally mandated versions in various countries).   There 

We could take a similar approach to FHIR (as with the link at the top of this thread) where what you see when you look at the publications are the most recent (current state) specifications.  But then you provide a separate location where the previously published versions are kept.

Github release links won't work for our purposes, since those resolve to a package (compressed) and not to individual files.

**Comment by JohnMoehrke** [comment]
If your dominant use-case is FHIR.. Please see the maturity model efforts going on in the IHE Documentation Workgoup. The stages before Final-Text are indeed version specific. IHE should resist allowing an IHE-Profile to go Final-Text when the standards it is profiling are not yet Normative. We should not be shooting our own foot. ITI has been very strict on keeping Supplements Trial-Implementation until the standard it is based is Normative.

**Comment by ToddCooper** [comment]
The Gemini team will take care of this need using another non-IHE site.
