### ISSUE TITLE
Images that are not converting

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#3]
discuss the problem, attempted solutions,

**Comment by msmock** [comment]
Dear Mary, dear John, 

tried the word to html export today but without success. The code produced looks like HTML but sadly it is totally corrupted. I got parsing errors in almost every line. 

I played around a bit and found an online converting tool at https://www.aconvert.com/document/pages-to-html/ <https://www.aconvert.com/document/pages-to-html/> which produced parseable HTML, including most of the images, tables with header styling and consistent item numbering and indenting. 

Processing does not work yet, but I will see if I can adopt it with reasonable effort. 

I’ll keep you up to date on the progress.   

@Mary: I would appreciate if you could convert a file and check, if the result looks good to you. 

Regards, 
Martin

**Comment by JohnMoehrke** [comment]
my export out of word produces valid xhtml. Did you use the the word "Export" menu choice and select "Other" type of output, then select "Web Page Filtered" as the output type? This is the recommendation on how to get the most minimal xhtml.
https://www.howtogeek.com/355674/how-to-save-a-microsoft-word-document-as-a-web-page/

**Comment by JohnMoehrke** [comment]
@costateixeira we have been using pandoc, but pandoc is not exporting table headers and figure headers. When we looked at a microsoft word export we see that they are included in the microsoft output.

**Comment by msmock** [comment]
Dear John, 

I tried all possible variants of word export. None worked on my private mac or business windows machine. But maybe because I don't have the latest versions. I don't remember the link. Can you post the link to your word generated HTML here? 

The online tool uses "Aspose.Words for .NET 17.1.0.0" as generator. Sure, a local solution not using online tools is preferred. 

We should finish the options of conversion tools soon, since otherwise we may run out of time with preparing the processing. 

Regards, 
Martin

**Comment by costateixeira** [comment]
Hi. In my case (pandoc) the headers are exported. The only thing that does
not get exported are the autonumbers, so what I have to do is to convert to
manual numbers just before exporting (CTRL+SHIFT+F9)

**Comment by JohnMoehrke** [comment]
@costateixeira  we have experience that we are working with . pandoc does the right thing most of the time, but we are dealing with the huge word documents from the ITI Technical Framework and pandoc fails too often leaving us with having to fixup by hand. Our observation during our meeting where the group discussed this was that microsoft word export did not fail in the location where pandoc did.

**Comment by JohnMoehrke** [comment]
I have added the word export to the repo as ms-vol1

**Comment by msmock** [comment]
Thanks for providing the file. 

It's displayed correctly in a browser but I cannot parse to xhtml due to xml errors, which the browser is able to ignore (browsers have many years of experience dealing with html errors in advance).

For example, if you search for keyword EN-US the first match is: 

<body bgcolor=white lang=EN-US link=blue vlink=purple>

which causes errors, since attributes must be enclosed with ". To parse without erros, it must read 

<body bgcolor="white" lang="EN-US" link="blue" vlink="purple">

instead.

**Comment by JohnMoehrke** [comment]
well that is disappointing.  they seem to use non quoted strings alot. Is this possibly a different flavor of html?

So how well does your other alternative export work?

**Comment by JohnMoehrke** [comment]
Note, I tried the word export with normal html (not filtered). It has the same issue, and is 7* bigger

**Comment by msmock** [comment]
The online export produces parseable content, but also deeply nested structures. For example, the heading of Volume 1  Section 5 looks like:  

      <h1 style="margin-top:12pt; margin-left:21.6pt; margin-bottom:3pt; text-indent:-21.6pt; page-break-before:always; page-break-after:avoid; font-size:14pt">
        <span style="font-family:Arial">5</span>
        <span style="font:7pt 'Times New Roman'">        </span>
        <a name="_Toc210747714" />
        <a name="_Toc214425604" />
        <a name="_Toc487039018" />
        <a name="_Toc488068119" />
        <a name="_Toc488068552" />
        <a name="_Toc488074879" />
        <a name="_Toc13752255">
          <span style="font-family:Arial">Patient Identifier Cross-referencing (PIX)</span>
          <span style="-aw-bookmark-end:_Toc210747714" />
          <span style="-aw-bookmark-end:_Toc214425604" />
          <span style="-aw-bookmark-end:_Toc487039018" />
          <span style="-aw-bookmark-end:_Toc488068119" />
          <span style="-aw-bookmark-end:_Toc488068552" />
          <span style="-aw-bookmark-end:_Toc488074879" />
        </a>
      </h1>

and has a number of parent <div> elements :-(. I currently don't know how to split that to files per section by processing. Still trying to figure that out.

**Comment by JohnMoehrke** [comment]
on images... ITI tended to use PPT for many of our diagrams. It is not hard to copy them out of the word into a standalone PPTX slide, save that as PPTX (for maintenance) and as SVG (for use). I have done this experiment with one diagram, and it worked fine. So we might need to just do this manually. Not that hard to do.

**Comment by keithboone** [comment]
> Thanks for providing the file.
> 
> It's displayed correctly in a browser but I cannot parse to xhtml due to xml errors, which the browser is able to ignore (browsers have many years of experience dealing with html errors in advance).
> 
> For example, if you search for keyword EN-US the first match is:
> 
> which causes errors, since attributes must be enclosed with ". To parse without erros, it must read
> 
> instead.

So, HTML isn't XML, it's an application of SGML (XML's predecessor), and can get away with things like not quoting attributes, not closing certain tags (those without content, such as <br>), or not declaring entities such as &nobr;.  To fix these issues, I have routinely used HTML Tidy or one of it's variants (there's a Java version) and add the necessary flags to force HTML generated from Word or other tools into clean XHTML.

**Comment by Mary** [comment]
hi, I think you've attached the wrong Mary. Thank you :)

**Comment by JohnMoehrke** [comment]
> hi, I think you've attached the wrong Mary. Thank you :)

sorry. It seems someone did an @ inclusion and you happen to have the github user of "Mary"

Should have been @MaryLJ

**Comment by JohnMoehrke** [comment]
closing this as we have a go forward plan in issue #5
