### ISSUE TITLE
chapter 4.2 is too big, needs to be broken down

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#30]
see the breakdown I have made in the wiki page for XDS
https://wiki.ihe.net/index.php/Cross-Enterprise_Document_Sharing#Vol._3

It would create many files, but I think this level of referenceability is needed. Possibly H4 could be done with #

**Comment by JohnMoehrke** [comment]
break out H4 in 4 into standalone html files.
add to contents the H4

**Comment by vassilpeytchev** [comment]
I disagree that 4.2 needs to be broken down. I suggest we leave it as is.

**Comment by JohnMoehrke** [comment]
@vassilpeytchev is considering a different way to make the content more accessible. This may result in a new issue covering the new model, and this item might be canceled.

**Comment by JohnMoehrke** [comment]
look at #29
