### ISSUE TITLE
How should we explain the dual publication

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#33]
* User navigating to profiles should understand what they are looking at
  * they should know that ITI is different
* They should know that PDF takes precedence if a difference is found
* They should know that Change Proposals must come thru the same old method?

**Comment by MaryLJ** [comment]
Perhaps we add a link to the HTML version at the same locations as the PDF version (on the ihe.net page) with the word PILOT or something similar.  Include "Instructions for use" wording that includes that the PDF is the bible (for now) and that all comments are (error, content, look and feel, navigation, etc.).

**Comment by JohnMoehrke** [comment]
should also have ihe.github.io point at this publication (https://ihe.github.io/)

**Comment by JohnMoehrke** [comment]
@lynnfel recommended today that the top of the HTML publication should warn the reader that this is experimental publication, reminding them that any conflicts with the PDF are not intended, and that the PDF is normative.
