### ISSUE TITLE
Add links for technical publication announcements

### ISSUE THREAD

**Issue by MaryLJ** [IHE/publications#342]
Add a link to subscribe to the technical publication announcements and a link to past publication announcements

**Comment by JohnMoehrke** [comment]
I thought that you were going to add details about how to subscribe to the RSS feed
https://profiles.ihe.net/fhir/publication-feed.xml

**Comment by MaryLJ** [comment]
created a separate issue to add details about how to subscribe to the RSS feed on the main publications (index) page. See #346
