### ISSUE TITLE
redirect wiki profiles to profiles.ihe.net

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#37]
The ITI published profiles should minimally be redirected to the profiles.ihe.net rather than the PDF publications

Possibly the duplication of the profile summary, actors/transactions, options, etc.. should be removed as the new html page is better maintained.

Possibly the wiki page for profiles might link to the html higher on the page? 
Possibly the wiki page for profiles might auto-redirect to the html page?

There is current information on the wiki page that is not part of the technical framework. Such as pointers to tests, examples, etc.

**Comment by MaryLJ** [comment]
Google Sheet to track progress of fixes for this issue is at https://docs.google.com/spreadsheets/d/1eM8OgzO8qGbc9Q8lEyBtwdALFOaYZN9W-AsyV6EnXWA/edit#gid=2021735577

**Comment by JohnMoehrke** [comment]
done
