### ISSUE TITLE
Unfortunate conventions for references within  Volume 2

### ISSUE THREAD

**Issue by lynnfel** [IHE/publications#41]
This is the current convention in PDF publication:  

If I am in Vol 2a and I want to refer to another section in 2a, I will say, "See Section 3.a.b"
If I am in Vol 2a and I want to refer to a section in Vol 2b, I will say "See ITI TF-2b: 3.y.z"

Ideally over time, in HLTM, these would all change to "See ITI TF-2: 3.f.g"

Here's an example which appears in ITI TF-2: 3.8.4.2.4:

See **Section 3.18.4.1.2.3.9** for details of how this message type affects results of a Registry Stored Query [ITI-18] transaction and the end of **ITI TF-2b: 3.42.4.1.3.3.2** to see how it affects the Register Document Set-b [ITI-42] transaction

**Comment by vassilpeytchev** [comment]
Another note for making links to sections - in both cases, make the link to include the leading words, e.g.

`See <a href="ITI-a.html#3.a.b">Section 3.a.b</a>`
`See <a href="ITI-y.html#3.y.z">ITI TF-2b: 3.y.z</a>`

If the text is "See Sections F.G.H and I.J.K" I change it to "See Section F.G.H and Section I.J.K" to make the links consistent, and easier to hit.

**Comment by lynnfel** [comment]
I agree with Vassil's suggestion.  There is inconsistency today that can be cleaned up over time.

**Comment by lukeaduncan** [comment]
Have cleaned up references to 2a, 2b, 2c in publications and IGs.  Some will happen at their next publication.
