### ISSUE TITLE
ITI announcement on Gender Harmony

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#428]
@MaryLJ 

We would like to add the following announcement onto the announcement you will eventually make for the ITI DSG JSON Signature public-comment. This a second concept on that announcement drawing attention to a project we are working on.
-----------------------------------------------------

**CP-ITI-1297:**

The HL7 Gender Harmony Project has developed a logical model to include information in electronic health records for supporting the care of gender and sex diverse patients. See https://hl7.org/xprod/ig/uv/gender-harmony/
This model includes requirements and examples for encoding sex and gender in HL7 v2.9.1, FHIR R5, and CDA. FHIR introduced the following extensions. See also https://hl7.org/fhir/R5/patient.html#gender.

IHE IT-Infrastructure is considering adopting of the HL7 information model. While the inclusion of Gender Harmony elements is not mandated, the CP aims to introduce a conditional requirement, stipulating that if concepts related to sex and gender are included, they must adhere to the methods defined by the Gender Harmony Project. The impacted IHE Profiles are: PDQ, PAM, XCA, XDS, PIX, XPID, PCF, PDQm, PIXm, and PMIR.

Note: While the HL7 Gender Harmony Project did not address v3, therefore we cannot address PIXv3, PDQv3, or XCPD. The ITI Technical Committee has acknowledged the importance of incorporating sex and gender information in XCPD for enhanced cross-community patient discovery. However, due to the absence of provisions within the base standard, no immediate action is being taken. Public comment is sought on this approach.

**CP-ITI-1297** is currently under development, we welcome participation in the development of the CP over the next few months. See: https://docs.google.com/document/d/1cSB7nPur0zEqptzYJsI5G-71exlnvFa8/edit?usp=drive_link&ouid=109672888359198923934&rtpof=true&sd=true

**Comment by JohnMoehrke** [comment]
@snichols001 -- please confirm the above wording.

**Comment by snichols001** [comment]
Looks good. Added ink to CP-ITI-1297

**Comment by JohnMoehrke** [comment]
This issue is tracking getting this information into the ITI announcement by Mary.
