### ISSUE TITLE
Open items for ITI-18

### ISSUE THREAD

**Issue by lynnfel** [IHE/publications#43]
Figure 3.18.4-1 is missing.  The png is missing from the media directory

3.18.4.1.2.3.5:  I adjusted the bullets because I think the  PDF TF is wrong.  Is the current content correct

3.18.4.1.2.3.11:  Under the "Returns" prompt, again, I think the TF is wrong.  Check my fixes.

3.18.4.1.3.3:  The example in this section lost the indenting that's in the PDF

**Comment by JohnMoehrke** [comment]
I fixed the missing graphic

Yes, I think your bullets are right

Yes, I think (if you mean  3.18.4.1.2.3.7.11 GetFolderAndContents) your bullets are right

I agree the indenting is lost... eventually we can fix ... but I don't think this is important....  One possible solution for fixing these is to externalize all the examples as XML content that we point at, with possibly bringing in in an iFrame. Others might just save the XML to implementers-material and link to the file.

**Comment by lynnfel** [comment]
I agree we don't have to fix the indenting now; as you suggest, we'll need to determine a general approach

**Comment by JohnMoehrke** [comment]
I created an issue to track this into next phase
