### ISSUE TITLE
SNIP, remove from www.ihe.net public comment

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#455]
The https://www.ihe.net/resources/public_comment/#IT shows SNIP as available for public-comment. given that it is a whitepaper/handbook, is it always open for public-comment. However we are not actively seeking comment at this time. Please remove this.

**Comment by MaryLJ** [comment]
The www.ihe.net page has been updated and the document has been removed.
See https://www.ihe.net/resources/public_comment/#IT.
