### ISSUE TITLE
ITI: DUB extensions to Public Comment

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#473]
https://github.com/IHE/ITI.DSUB_extensions

Note:
1. The changes will be moved into proper WORD DOCX format by @dbabato  by November 1st

**Comment by dbabato** [comment]
Hello, 
the document "IHE_ITI_Suppl_DSUB_Extensions_Rev2-0_TI_2024-10-25.docx" in a WORD DOCX format is uploaded at the link:
[IHE_ITI_Suppl_DSUB_Extensions_Rev2-0_TI_2024-10-25.docx](https://github.com/IHE/ITI.DSUB_extensions/blob/main/IHE_ITI_Suppl_DSUB_Extensions_Rev2-0_TI_2024-10-25.docx)

**Comment by JohnMoehrke** [comment]
@MaryLJ This is ready for you to start work on.
