### ISSUE TITLE
Indent fix needed in Vol 2 Appx C Sec C.2.4

### ISSUE THREAD

**Issue by lynnfel** [IHE/publications#48]
In the list of ERR elements, I have tried and failed to fix the indenting for  the values allowed for ERR-2.5, ERR-3.1 and ERR-3.2

Help.

**Comment by vassilpeytchev** [comment]
I think the best way is to use the built in XY-grid from the framework. The grid is made of 12 columns, and gives us a lot of flexibility of arranging "cells" of varying width. For this particular case, the following works:

      <p>
        
        <div class="grid-x margin-x align-center">
          
          <div class="cell small-12 medium-10">
            
            <div class="grid-x align-left">
              
              
              <div class="cell small-3">ERR-2.1:</div>
              <div class="cell small-1"><strong>MSH</strong></div>
              <div class="cell small-8"></div>
              
              <div class="cell small-3">ERR-2.2</div>
              <div class="cell small-1"><strong>1</strong></div>
              <div class="cell small-8"></div>
              
              <div class="cell small-3">ERR-2.3</div>
              <div class="cell small-1"><strong>9</strong></div>
              <div class="cell small-8"></div>
              
              <div class="cell small-3">ERR-2.4</div>
              <div class="cell small-1"><strong>1</strong></div>
              <div class="cell small-8"></div>
              
              <div class="cell small-3">ERR-2.5</div>
              <div class="cell small-1"><strong>1</strong></div>
              <div class="cell small-8">if an unrecognized message type</div>
              
              <div class="cell small-3"></div>
              <div class="cell small-1"><strong>2</strong></div>
              <div class="cell small-8">if an unrecognized trigger event</div>
            </div>
          </div>
        </div>
      </p>
      <p>The components of Field ERR-3 of the acknowledgement shall be populated as follows.</p>
       
      <p>
        <div class="grid-x margin-x align-center">
          <div class="cell small-12 medium-10">
            <div class="grid-x align-left">
              
              <div class="cell small-3">ERR-3.1</div>
              <div class="cell small-1"><strong>200</strong></div>
              <div class="cell small-8">if an unrecognized message type</div>
              
              <div class="cell small-3"></div>
              <div class="cell small-1"><strong>201</strong></div>
              <div class="cell small-8">if an unrecognized trigger event</div>
              
              <div class="cell small-3">ERR-3.2</div>
              <div class="cell small-9"><strong>Unsupported message type</strong> or</div>
              
              <div class="cell small-3"></div>
              <div class="cell small-9"><strong>Unsupported trigger event</strong> as appropriate</div>
              
              <div class="cell small-3">ERR-3.3</div>
              <div class="cell small-9"><strong>HL70357</strong></div>
            </div>
          </div>
        </div>
      </p>

**Comment by lynnfel** [comment]
Looks great!  thank you
