### ISSUE TITLE
Release TI - ITI PDQm 3.1.0 - integrated CP-ITI-1314

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#483]

**Comment by JohnMoehrke** [comment]
@MaryLJ Given this will be a minor change to integrate a CP. Do you think you need to review at the IG level prior to me building for publications? Or should I build this for publication?

**Comment by MaryLJ** [comment]
It should be OK to build this now.

 

Mary

 

Mary Jungers | Documentation Specialist 

IHE International | IHE.net
