### ISSUE TITLE
Publish Devices PCIM Supplement Rev. 2.2.

### ISSUE THREAD

**Issue by MaryLJ** [IHE/publications#499]
Publish the updated Devices PCIM supplement (long form) Revision 2.2 for Trial Implementation.

**Comment by MaryLJ** [comment]
It was going to be this Thursday but I can ask if they can wait until next Thursday

 

Mary Jungers | Documentation Specialist 

IHE International | IHE.net

**Comment by JohnMoehrke** [comment]
we have already integrated our 12/12 changes into publications repo. Thus you can't make a tag on publications that just has devices, and if you do make a tag, it means that the 12/12 tag will not include the notes about the ITI stuff.
