### ISSUE TITLE
Manual extract of images 

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#5]
Given that the automatic extraction process used does a poor job of extracting images, we need a set of people who are willing to do manual extraction.

**Priority**
1. Images that simply did not get extracted at all
2. Low quality images
3. Images that we do have as powerpoint slides as embedded OLE objects in the DOCX --> extract into PPTX slide so we have editable content, use Powerpoint to also save as PNG as high quality image for html use
4. Images that we do have as word draw objects -- extract into PPTX slide so we do have an editable version in the future

Save each image as a file using the filename of the Figure number (e.g. "Figure_1.2.3-4.pptx", and "Figure_1.2.3-4.png") -- in the volume "media" directory (e.g.  ITI/Volume1/media)

**Comment by JohnMoehrke** [comment]
The goal is to get a fully editable copy of the figure in PPTX format, and a browser ready in PNG. The result should be a set of graphic objects that you can move around, edit the text, etc. 

Some figures were originally drawn using powerpoint, so simple copy-paste  out of the word document and into a standalone powerpoint slide deck (one slide per file) should work.. but experimentation so far is mixed. I think these are originally drawn with word "Draw", so they don't seem to copy as richly using simple copy-paste.  Older drawings often use word "Draw", as that was the preference back then. 

To get the feel for the following procedure try this on the Figure 3.1-1 in Volume 1. 

Draw Objects:
On my version of office tools and Windows 10.
1. Start with latest WORD docx files. Find all current DOCX files in the IT-Infrastructure github in the ForPublications folder
      https://github.com/IHE/IT-Infrastructure/tree/master/ForPublication
2. Double click on the figure in word, this opens up a new window with the Draw app. (note there is no indication this is "Draw" but it is clearly different UI and different menu choices) 
3. In the Draw app I used the "Editing" tool to select everything, (This is not in the normal menu location, but is a graphic button on the toolbar)
4. Copy, 
5. Paste that into powerpoint. This resulted in a powerpoint slide with these individual objects. 
6. Save as the figure (filename instructions above)
7. Save-As (or Export) to PNG with the same filename.
8. put both files into the media folder of the volume folder (instructions above)

**Comment by JohnMoehrke** [comment]
| Volume | number of images to convert | Who is converting |
|----------|---------------------------------|---------------------|
| Volume 1  | 134 | - |
| Volume 2a | 44 | John |
| Volume 2b | 74 | - |
| Volume 2x | 16 |  - |
| Volume 3 | 42 | - |
| Volume 4 | ?? | - |

**Comment by lynnfel** [comment]
I can take Volume 1

**Comment by JohnMoehrke** [comment]
I have finished Volume2a (note not converting the spaceship diagrams). One I converted into PlantUML because the graphic was clearly from PlantUML. So we now have that in PlantUML editable form.

**Comment by mattblackmon** [comment]
I will take 2b. Deadline?

Matt

Matt Blackmon, Testing Programs Engineer

My calendar availability: https://tinyurl.com/y3r9s2pz

The Sequoia Project® - Connected we stand!
________________________________________________________________________________________


Contact: +1-865-281-1873
mblackmon@sequoiaproject.org<mailto:mblackmon@sequoiaproject.org> | sequoiaproject.org<http://sequoiaproject.org/>









[signature_852161297][signature_324521152]

**Comment by JohnMoehrke** [comment]
Matt, Excellent choice. Reminder, do NOT bother with the star-ship enterprise diagrams at the beginning of each transaction,

**Comment by JohnMoehrke** [comment]
NOTE: When updating the html files to refer to these new Figure files... Remove the width and height. The current CSS will auto-scale to the browser size.
e.g.
   Current:
>      <h3 id="3.9.4">3.9.4 Messages</h3>
>      <img src="media/amdr0-jc4sx.023.png" width="528" height="278" alt="" />
>      <p class="figureTitle">Figure 3.9-1: Get Corresponding Identifiers Sequence</p>
    Improved:
>      <h3 id="3.9.4">3.9.4 Messages</h3>
>      <img src="media/Figure_3.9-1.png"  alt="" />
>      <p class="figureTitle">Figure 3.9-1: Get Corresponding Identifiers Sequence</p>
      
on the starship, I just commented out the image
>  
although deleting the line is fine too

**Comment by MaryLJ** [comment]
I will start with 2x and move on to 3 if needed. When are you hoping to have the conversion completed?

**Comment by JohnMoehrke** [comment]
Timing is hard to push on volunteers. I think we have enough done already to know that this will work. Thus the hard deadline is our next face-to-face where we will want to get approval for publication to the general public. Given that, it would feel good to have all these converted and using the new graphics by the end of August.

**Comment by msmock** [comment]
2b has an error I didn’t recognize so far. The appendices override the first transactions. Please wait until I could fix this, since I must override the files in the repository. I’ll do it next week.

**Comment by JohnMoehrke** [comment]
> 2b has an error I didn’t recognize so far. The appendices override the first transactions. Please wait until I could fix this, since I must override the files in the repository. I’ll do it next week.

We should still be able to extract out the images using the pattern. We will just not edit the html to use the new images.

**Comment by JohnMoehrke** [comment]
Volume 2a is done. all images are extracted and html is updated to use those images.

**Comment by JohnMoehrke** [comment]
Volume 3 -- I found only 2 figures that had content to them. All the other 46 images are flat images with no structure to recover. Thus Volume 3 will be just using the graphics that were made by the automatic export.
I do have a query out to see if anyone has the source for these figures. Many of them are UML or logic diagrams that would be really good to have in an editable form (e.g. PlantUML).

**Comment by JohnMoehrke** [comment]
Just noticed that Volume 3 includes graphics (not figures) for sample code boxes. about 10 of the images. @msmock is this a conversion task?

**Comment by MaryLJ** [comment]
For figures that were inserted in the TF Volume as pictures, how should we handle? See Figure M.2-1 in Volume 2x at https://ihe.github.io/publications/ITI/TF/Volume2x/ch-13.html. The media file is already a png (media/ahwre-n9c4j.003.png) but there is no editable version. What are the plans to create the editable version?

**Comment by JohnMoehrke** [comment]
I have similar challenges in Volume 3. I have tried to search out old versions of the supplement to see if there ever was a version of these in editable form... but have not found them. So I think the following options:
1. Do nothing. Use the images that were exported -- the drawback is that those exports are not very high quality.
2. Keep original PNG files, but rename them to the filename convention -- advantage is consistency of figures referencing
3. Export them using mostly the same procedure to get a PPTX, and new PNG -- this ends up with better quality.

For now I am thinking that 3 is the right solution. It is more work, but it sets up a more consistent pattern. It also shows our future-self that we tried and did not find an editable form.

what do you all think?

**Comment by MaryLJ** [comment]
Volume 2x is done. The following images were exported as non-editable (because they were in Word as pictures):
M.2-1, O.1.1-1, O.1.2-1, O.1.3-1, O.2.1-1, O.2.2-1, O.2.3-1, O.2.4-1

**Comment by mattblackmon** [comment]
Martin,

 

I don’t know this impacts my image extraction greatly, but did you get a chance to re-upload 2b? I think the date on the repo is still late July

 


Thanks!
Matt

**Comment by JohnMoehrke** [comment]
Yes. He confirmed last week

**Comment by JohnMoehrke** [comment]
Mary found a method of cropping the exports from powerpoint

If the image was pasted into a ppt slide as an uneditbale image (i.e., the source was already an image that could not be edited):

1. Click on the image to select it
2. Right click on the selected image and select Save as Picture
3. In the Save As Picture dialog box that appears, enter the File name and select PNG as the Type
4. Click Save

If the image is an editable ppt slide (made up of text and objects), then:

1. Navigate to the Home Tab
2. In the Editing Group (upper right side of the ribbon), click on the little down arrow of the Select option
3. Click on Select All  to select all the text and objects
4. Once all text and objects are selected, right click inside one of the shapes and select Save as Picture (make sure that all the text and objects are still selected)
5. In the Save As Picture dialog box that appears, enter the File name and select PNG as the Type
6. Click Save

**Comment by MaryLJ** [comment]
I am going to start extracting images from 2b. If anyone has already extracted some, please let me know so we do not duplicate efforts. Thank you.

**Comment by mattblackmon** [comment]
Hello Mary,

I have almost completed 2b and hope to finish it Saturday.

Matt

Matt Blackmon, Testing Programs Engineer

My calendar availability: https://tinyurl.com/y3r9s2pz

The Sequoia Project® - Connected we stand!
________________________________________________________________________________________


Contact: +1-865-281-1873
mblackmon@sequoiaproject.org<mailto:mblackmon@sequoiaproject.org> | sequoiaproject.org<http://sequoiaproject.org/>









[signature_1078391191][signature_1316392105]

**Comment by MaryLJ** [comment]
Great, thank you for letting me know.

 

Mary

**Comment by MaryLJ** [comment]
Will extract Volume 4 images

**Comment by JohnMoehrke** [comment]
I think I did that


John Moehrke - Architect: Standards - Interoperability, Privacy, and
Security for Bylight.com
https://healthcaresecprivacy.blogspot.com

**Comment by JohnMoehrke** [comment]
Hey @mattblackmon whats up???

**Comment by JohnMoehrke** [comment]
Hey @mattblackmon are you done?
