### ISSUE TITLE
profiles..ihe.net redirects support

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#52]
minimally we need
http://ihe.net/fhir/
redirected to
https://profiles.ihe.net/fhir/

but there might be other things that come up over time.

**Comment by JohnMoehrke** [comment]
still broken

**Comment by JohnMoehrke** [comment]
ftp.ihe.net --> profiles.ihe.net

**Comment by MaryLJ** [comment]
Did not mean to close this issue, though I was just replying to a comment.

**Comment by JohnMoehrke** [comment]
Mary has the power now. So I think this is now closed.
