### ISSUE TITLE
Harder to find some TI supps in profiles.ihe.net

### ISSUE THREAD

**Issue by lynnfel** [IHE/publications#57]
In the layout on profiles.ihe.net, in the Vol 1 area, I can easily find the TI Supplements that are stand-alone profiles (eg RMU, SVCM...).   

However:
- if a TI supplement modifies an existing profile (RESTful ATNA, XDS-MU, DSUB extensions, more), a user has to go into the Vol 1 text of the parent Vol 1 profile chapter, and then find a link to the supplement at the top
- -->  ok, but maybe not obvious to a novice reader?
- we have lost the view we get on ihe.net that easily tells us "what's in TI in the ITI domain?"

**Comment by JohnMoehrke** [comment]
add a supplements section on the ITI home page listing all supplements, like we have on www.ihe.net.
