### ISSUE TITLE
Add note to index page with pointer to Final Text ITI CPs

### ISSUE THREAD

**Issue by lynnfel** [IHE/publications#59]
On our Index the the ITI Technical Framework, the text that appears on ihe.net with a pointer to approved ITI CPs. 

An initial discussion in the html publishing call determined that the text should appear in a separate 'bubble' under the existing text "The current version of the ITI TF is published here...."

See 2 screenshots below for location and text to add.
![1](https://user-images.githubusercontent.com/47753616/104332844-3b439d00-54b6-11eb-8fd8-9a0845fd269c.jpg)
![2](https://user-images.githubusercontent.com/47753616/104332883-43034180-54b6-11eb-917a-0f562cb9de81.jpg)

**Comment by JohnMoehrke** [comment]
After Volume 4

Final Text (Approved) Change Proposals
IMPORTANT NOTE: In addition to the Technical Framework Volumes and Trial Implementation Supplements listed below, implementers should also review Final Text Change Proposals (CPs) in preparation for IHE Connectathons. An index of approved CPs is found here.

https://docs.google.com/spreadsheets/d/13CrWhlTQJqH5gilo91Z_DWSqgPxGjS5tM9YnJb-qbIU/edit#gid=388571237

**Comment by lynnfel** [comment]
propose this wording: 

Final Text (Approved) Change Proposals:  Change Proposals (CPs) are periodically integrated into ITI Technical Framework Volumes and Trial Implementation Supplements.  A log of approved CPs is found <a href="https://docs.google.com/spreadsheets/d/13CrWhlTQJqH5gilo91Z_DWSqgPxGjS5tM9YnJb-qbIU/edit#gid=388571237">here target="_blank"</a>. Final Text CPs may be testable IHE Connectathons before they are integrated into Technical Framework documents.
