### ISSUE TITLE
how to work archiving past versions?

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#6]
1. When a new version is published, the prior is committed to a PDF and thus handled similar to current archive model
2. Copy current html into an archive folder into a version specific folder as the full html
3. Only tag the github release, so send readers to github
4. some other?

**Comment by lukeaduncan** [comment]
Archiving is outlined here:  https://profiles.ihe.net/ITI/index.html#1.7
Further info here:  https://github.com/IHE/publications/wiki/Revision-Management
