### ISSUE TITLE
ITI Appendix 2:W should be promoted to a general introduction chapter

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#60]
The material in appendix W should be a general appendix

**Comment by JohnMoehrke** [comment]
Dependent on #66 
Will need to get DCC approval of the move of this content to general
likely an appendix in general intro? Or should it be a chapter?
Will need to update ITI appendix to point at the moved content

**Comment by lynnfel** [comment]
I agree this should be done as soon as we can make the wheels turn
