### ISSUE TITLE
Improve the General Intro pages

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#66]
* look and feel
* promote the html rendered and remove PDF on www.ihe.net

**Comment by vassilpeytchev** [comment]
The appendices don't seem to have been converted. Is this expected to happen soon?

**Comment by JohnMoehrke** [comment]
Which? And converted in what way? I don't know of anything planned.

**Comment by vassilpeytchev** [comment]
The General Intro Appendices are not converted into HTML, they are still PDF. Would there be an effort to convert?

**Comment by MaryLJ** [comment]
The General Introduction was converted and published at https://profiles.ihe.net/GeneralIntro/. All the appendices except A, B and D were also converted and published. There are updates in the works so I asked to wait on converting those three.

 

Mary

**Comment by JohnMoehrke** [comment]
https://github.com/IHE/publications/tree/master/GeneralIntro
