### ISSUE TITLE
Provide users a way to get a PDF extract

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#7]
IHE-USA has done a survey of our IHE audience. There was equal parts of responses that were very happy we were going to HTML, as there was people very upset. There was strong evidence that we must be able to provide a function to extract into PDF.

1. Some were wanting us to continue to support full volume based PDF. (63%)
2. Some were wanting per-profile based PDF. (75%)
3. Some were wanting per-page based PDF (which is simply a browser print).

There was concern that the HTML publication would not be as paper-printout friendly. There was concern that HTML would limit ability to use offline.

PS. Likely same choices as above to produce a ZIP of the HTML (not PDF) might satisfy some worried about offline access, or their ability to capture specifications.

**Comment by costateixeira** [comment]
I suggest we find ways to make the publication printer-friendly, then we can try to print the content (or parts of it) to pdf.

**Comment by lukeaduncan** [comment]
There is no expectation that we will support this.  There are tools to accomplish some of this, although none are perfect.
