### ISSUE TITLE
search is not finding things

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#71]
today went looking for "XDSStoredQueryParamNumber"

resulting in 
https://www.google.com/search?q=site%3Ahttps%3A//profiles.ihe.net%20XDSStoredQueryParamNumber

this found one instance in volume 3, but only found it in the example in volume 3. This did not find these in ITI-18.

The instances of this in ITI-18 are simple strings, so unclear why they would not be found.

**Comment by JohnMoehrke** [comment]
upload a map to google to help it understand how to index.

**Comment by JohnMoehrke** [comment]
need to assign ownership of this site google search optimization. @ccarr

**Comment by JohnMoehrke** [comment]
committee will work with assigned person to help with search terms and such.

**Comment by JohnMoehrke** [comment]
https://search.google.com/search-console/about

**Comment by MaryLJ** [comment]
When looking into this issue, see https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap?sjid=7404599598628858023-NA&visit_id=638283958723565512-3042287346&rd=1

**Comment by costateixeira** [comment]
can we bring an alternative to google search?

**Comment by JohnMoehrke** [comment]
@costateixeira we provide robots.txt; so ALL search index robots are given the right detail on how to index, so they all work.

We today do not support much of any search capability beyond that. 

This issue is only about a search box in the ITI Technical Framework. It does not appear anywhere else.

**Comment by JohnMoehrke** [comment]
This appears to now work. Presume there was delay in google indexing.
