### ISSUE TITLE
General Intro should define normative words

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#80]
The General Intro should define the normative words for us. This seems done in some domains, but not all of them.  

Likely section 7, or appendix E

-------
Here is the text from Cardiology and Radiology Technical Frameworks

H2 Normative versus informative contents of the Technical Framework

Most parts of the Technical Framework describe required or optional characteristics of
Integration Profiles, Actors and Transactions: these are normative. For a better understanding of
the text, there also exist illustrating parts in the Technical Framework that are informative and
non-normative.

According to IETF RFC 2119, certain words indicate whether a specific content of the Technical
Framework is normative: either required (e.g., “must”, “required”, “shall”) or optional (e.g.,
“may”, “recommended”). Informative content does not contain these key words.

**Comment by DavidPyke** [comment]
RFC 2119 has been updated by 8174 which has been combined into BCP-14.  Having an acknowledgement of one of these (preferably BCP-14) would make it clear.  However a review of all docs to ensure that capitalization has been adhered to should be done.

**Comment by JohnMoehrke** [comment]
@MaryLJ should this be handled by the documentation workgroup?

**Comment by MaryLJ** [comment]
I can work with you to add text to the General Intro.

**Comment by JohnMoehrke** [comment]
add to general Intro, appendix E, section E.1 a new section E.1.1

H2 E.1.1 Normative versus informative contents of the Technical Framework

Most parts of the Technical Framework describe required or optional characteristics of
Integration Profiles, Actors and Transactions: these are normative. For a better understanding of
the text, there also exist illustrating parts in the Technical Framework that are informative and
non-normative.

According to IETF BCP-14 (currently  RFC 2119 and RFC 8174), certain words indicate whether a specific content of the Technical
Framework is normative: either required (e.g., “must”, “required”, “shall”) or optional (e.g.,
“may”, “recommended”). Informative content does not contain these key words.
