### ISSUE TITLE
Appendices A, B, C, and the Glossary should be removed from TF-1 

### ISSUE THREAD

**Issue by MaryLJ** [IHE/publications#88]
Remove the content (and replace with Intentionally Left Blank or similar) from TF-1. These four items are part of the General Introduction and should not be duplicated in TF-1. Currently, the content that is in TF-1 differs from what is published as part of the General Intro.

Alternatively, leave the headings but link to the General Intro Appendices A, B, C, and Glossary content.

**Comment by JohnMoehrke** [comment]
change the link in ITI A, B, C to a deep link to the General Intro A, B, C
remove the Glossary text. Leave a Glossary text with link to the general intro glossary
