### ISSUE TITLE
General Intro - archives of web site

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/publications#93]
Provide instructions on how to get to archived versions of the profiles web site.

**Comment by JohnMoehrke** [comment]
should be on the GeneralIntro section, but covers whole web site

**Comment by JohnMoehrke** [comment]
pre-web (PDF) archives may be mentioned in general

**Comment by jlamy** [comment]
Does this issue imply archived versions are already available, we just need to explain how to get to them? If yes, does it just refer to zipped archives, or actual IHE-hosted archive HTML such that someone can use a permalink to a particular section in a particular release?

**Comment by JohnMoehrke** [comment]
it refers to official archives in github. Yes those are available as zips. The only official publication from IHE of "Final Text" is the "current". IHE makes archives available only for historic purposes. Conformance claims are always to "current", never to a version of Final Text.
